In [1]:
#Zomato Database Build

In [2]:
# Dependencies and Setup
import requests
import json
import pandas as pd
import time
from zkeys import zkey

In [3]:
#Declare variables
id_no = []
name = []
price_range = []
review = []
phone = []
reservations = []
rating = []
counter = 20

In [4]:
#Assign API key
api = zkey
headers = {'user-key': api}
#Toronto neighbourhoods 
entity_ids = (87071, 87081, 87091, 87161, 87191, 87221, 87241, 87281, 87351, 
              87361, 87391, 87401, 87441, 87701, 87861, 87871, 87881, 89161, 87891)

In [13]:
#Loop through subzones
for entity_id in entity_ids:
    start=1
    count=20
#Loop through two pages of results
    for c in range(4):
        url = f'https://developers.zomato.com/api/v2.1/search?entity_id={entity_id}&entity_type=subzone&start={start}&count={count}'
        response = requests.get(url, headers=headers)
        response_df= json.loads(response.text)
        #print(url)
        #add a one second interval between queries
        time.sleep(1)

        #Populate the dataframe
        for r in response_df['restaurants']:
            restaurant=r['restaurant']
            id_no.append(restaurant['id'])
            name.append(restaurant['name'])
            price_range.append(restaurant['price_range'])
            phone.append(str(restaurant['phone_numbers']))
            reservations.append(str(restaurant['has_table_booking']))
            review.append(restaurant['user_rating']['votes'])
            rating.append(restaurant['user_rating']['aggregate_rating'])

        #set the next page to pull
        start = start+20
        count = count+20

In [15]:
zomato_df= pd.DataFrame(data={"name":name, "id": id_no, "phone": phone, "reservations": reservations, 
                              "price_range": price_range, "review": review, "rating": rating })
zoamto_df=zomato_df.sort_values('id')
zomato_df.head(25)
len(zomato_df)

1500

In [16]:
phones = zomato_df['phone']

In [17]:
print (phones)

0                          +1 (416) 961-4642
1                          +1 (647) 748-4225
2       +1 (416) 963-6000, +1 (416) 963-6000
3       +1 (416) 551-9929, +1 (416) 551-9929
4                          +1 (416) 962-2822
5                          +1 (416) 968-2828
6                          +1 (416) 927-0077
7                          +1 (416) 923-9992
8                          +1 (416) 975-1100
9                          +1 (416) 971-9666
10                         +1 (416) 926-0953
11      +1 (416) 921-1471, +1 (416) 921-1471
12                         +1 (416) 926-0110
13                         +1 (416) 901-8869
14                         +1 (416) 925-1903
15                         +1 (647) 348-7000
16                         +1 (416) 922-2345
17                         +1 (416) 961-8349
18                         +1 (416) 960-3434
19                         +1 (416) 975-3948
20                         +1 (416) 923-3323
21                         +1 (416) 944-2637
22                         +1 (416) 849-1499
23                         +1 (416) 923-5716
24                         +1 (416) 969-1221
25                         +1 (647) 348-7000
26                         +1 (416) 785-9100
27                         +1 (416) 961-4333
28                         +1 (416) 961-1893
29                         +1 (416) 924-4967
                        ...
1470                       +1 (416) 439-0000
1471                       +1 (416) 782-0782
1472                       +1 (416) 645-0304
1473                       +1 (416) 654-0967
1474                       +1 (416) 653-4825
1475                       +1 (416) 460-5183
1476                       +1 (416) 614-8686
1477                       +1 (416) 782-7850
1478                       +1 (416) 604-1888
1479                       +1 (416) 247-3333
1480                       +1 (416) 787-1784
1481                       +1 (647) 348-3493
1482                       +1 (416) 244-8219
1483                       +1 (416) 913-1742
1484                       +1 (416) 763-2478
1485                       +1 (416) 762-1271
1486                       +1 (647) 350-9444
1487                       +1 (416) 240-8800
1488                       +1 (416) 767-8118
1489                       +1 (416) 766-6667
1490                       +1 (416) 653-2424
1491                       +1 (416) 656-6632
1492                       +1 (416) 653-3030
1493                       +1 (647) 344-1335
1494                       +1 (647) 224-3805
1495                       +1 (416) 551-0835
1496                       +1 (647) 344-2213
1497                       +1 (416) 652-0022
1498                       +1 (416) 769-8065
1499                       +1 (416) 249-7777
Name: phone, Length: 1500, dtype: object

In [26]:
phones_new = phones.str.split(',').str[0]

In [27]:
phones_new = [p.replace(' (', '') for p in phones_new]
phones_new = [p.replace(') ', '') for p in phones_new]
phones_new = [p.replace('-', '') for p in phones_new]

In [28]:
print (phones_new)

['+14169614642', '+16477484225', '+14169636000', '+14165519929', '+14169622822', '+14169682828', '+14169270077', '+14169239992', '+14169751100', '+14169719666', '+14169260953', '+14169211471', '+14169260110', '+14169018869', '+14169251903', '+16473487000', '+14169222345', '+14169618349', '+14169603434', '+14169753948', '+14169233323', '+14169442637', '+14168491499', '+14169235716', '+14169691221', '+16473487000', '+14167859100', '+14169614333', '+14169611893', '+14169244967', '+14169639864', '+14168234719', '+16477481770', '+14169670000', '+14166460705', '+14169719666', '+14169607817', '+16473443353', '+14163233696', '+14164286641', '+14168506135', '+14169624000', '+18553255781', '+14166139660', '+16473512235', '+14169622825', '+14169252143', '+14169638444', '+14169243223', '+16474369472', '+14165868086', '+14165042253', '+16477484464', '+14167926620', '+14169648665', '+14162020001', '+16473473618', '+14169677676', '+16473454214', '+18882181040', '+14169232882', '+14169340881', '+14169228822', '+18445486223', '+14169636667', '+14169618351', '+14166426364', '+14169634330', '+14169620275', '+14169619704', 'Not available for this place', '+14169440910', '+14163230636', '+14169228585', 'Not available for this place', '+14169298829', '+14165131118', '+14169209356', '+14169229778', '+14167920481', '+16472884710', '+14163625411', '+14169014724', '+14168157325', '+14164898922', '+16472536225', '+14165984719', '+16476600909', '+14162059836', '+14162059808', '+16473481166', '+16477480222', '+14165992873', '+14169350400', '+16472884715', '+14165519221', '+16474358365', '+14162602222', '+14165994442', '+16477888294', '+16473447326', '+14169774461', '+14168502855', '+16472538000', '+14162639850', '+14168600606', '+14162608414', '+14163480099', '+14169719155', '+14165990299', '+14165510433', '+16473527476', '+14165968080', '+14169778840', '+14165962240', '+14162049588', '+14165997246', '+14169717242', '+14167406622', '+16477483211', '+14162605100', '+14165978142', '+14165852121', '+14169791010', '+14165982672', '+14162600200', '+14169716626', '+16472538000', '+14169773064', '+14165984455', '+16473481066', '+14169772333', '+14166231975', '+14165728008', '+14165993868', '+14166375465', '+14165994678', '+14165995262', '+14165978839', '+14163513311', '+14165959100', '+14164084064', '+14164932786', '+14165952525', '+14163249174', '+14169772855', '+16472538000', '+14168833431', '+16479273900', '+14165951958', '+14169778778', '+14167030030', '+14165068886', '+14165972695', '+14165960063', '+16477483210', '+14165998828', '+14165961444', '+14169793005', '+16477483446', '+14165968600', '+16473525639', '+16473476286', '+14165970335', '+14165978838', '+14163663600', '+14169239867', '+14169289041', '+14169770303', '+16473472712', '+14169238784', '+14162639800', '+14169776677', '+14165852929', '+14169235438', '+14169256176', '+14169017339', '+14165982800', '+14169776748', '+16473523390', '+14163488938', '+14169231888', '+14169206288', '+16473408406', '+16473493833', '+14165930999', '+16473515128', '+14169774338', '+14168503179', '+14169798529', '+14169793447', '+14165955001', '+14169662424', '+14169726623', '+16477486666', '+14169608898', '+14168471007', '+14163518000', '+16477485683', '+14163401350', '+16473524770', 'Not available for this place', '+14165983339', '+16477483866', '+14169687054', '+14169698988', '+14169225551', '+14166468800', '+14165130002', '+14165938880', '+14169233354', '+14169713331', '+14163682695', '+14166623546', '+16477482886', '+16473450455', '+14169298893', '+14169341480', '+14163407887', '+14165970155', '+14165060753', '+14163239770', '+14165991989', '+14169224343', '+16474359464', '+14169775044', '+16473500111', '+14162602116', '+14169673388', '+14163100001', '+14165996161', '+14165979502', '+16477489100', '+14163488869', '+14169011973', '+14169778989', '+16473505883', '+14165852788', '+14169717888', '+14169612227', '+14165047867', '+14165049669', '+14163638105', '+14165966405', '+14169791990', '+14163660200', '+14163670505', '+14167921878', '+14163685151', '+14165043939', '+14168651600', '+14168662127', '+14165966660', '+14168491808', '+16476600999', '+14165984730', '+14166013533', '+14165992822', '+14169294900', '+14163624111', '+14166033333', '+16473516153', '+14168621175', '+14169791200', '+16473487000', '+14165997662', '+14163488886', '+16473472222', '+16473508666', '+14163418880', '+14165048155', '+14167032800', '+14169012289', '+14165861331', '+14168684800', '+14163687258', '+14165997746', '+14165048942', '+14167928858', '+16473477222', '+14163662873', '+14165049434', '+16472771187', '+16473521200', '+14163040767', '+14162030999', '+14163647227', '+14169795464', '+14165955155', '+14167033377', '+14162030222', '+14169470404', '+14162038456', '+14167772800', '+14168627737', '+14165047131', '+14163645137', '+16473455288', '+14163648833', '+14162037990', '+16473473647', '+16473522623', '+14168480057', '+14164518736', '+14165049311', '+16473518844', '+14163632223', '+14165517540', '+14163638388', '+14165997468', '+14165999995', '+16479334515', '+14167037401', '+14165464991', '+14165041045', '+14167822000', '+14165048293', '+16479513331', '+14165048586', '+14162639999', '+14169770601', '+14163400472', '+14162600500', '+14162170167', '+14169796763', '+14164637700', '+14169796688', '+14166409197', '+14165910863', '+14165932766', '+14165961908', '+14165971175', '+14165968787', '+14169772929', '+14167923838', '+14168505616', '+14169772788', '+14165930885', '+16473454439', '+16478598998', '+14165955222', '+14165984514', '+14162051001', '+16473468846', '+14165972580', '+14165982475', '+16473472812', '+14163575404', '+14169790500', '+16473473883', '+16473516555', '+14167928885', '+14163458729', '+14165857842', '+14165060777', '+16473510800', '+14165918697', '+14169791776', '+14165984226', '+14166402761', '+14165936265', '+14164323139', '+14169718885', '+16477485788', '+14165871100', '+14169168170', '+14165912188', '+16473482600', '+14169777000', '+14165980598', '+14169792884', '+14165517786', 'Not available for this place', '+16477486622', '+14165918965', '+14168503768', '+14163517231', '+14162609988', '+14162600189', '+14166278400', '+14169714263', '+14162171111', '+14165864800', '+14165979333', '+14163401838', '+14169776607', '+18664390439', '+14165069138', '+14162609662', '+14163418828', '+14165991361', '+16473482348', '+14165918430', '+14169715050', '+16473457360', '+14165969700', '+14165931477', 'Not available for this place', '+14165513307', '+14165959438', '+14162172008', '+14166033366', '+14165934274', '+14162600097', '+14165981817', '+16477488108', '+14162360018', '+14169771128', '+14169771922', '+14165861241', '+14169137487', '+14165968898', '+14169770056', '+16473436647', '+14169773909', '+16477480990', '+14169778080', '+14165939998', '+16473542473', '+16475014505', '+14165951881', '+14163517188', '+14167038330', '+14165911340', '+14165043025', '+14162030088', '+14169011510', '+16478898770', '+14165950327', '+14165983222', '+14169278885', '+14166033811', '+14165994625', 'Not available for this place', '+14168622266', '+14165969053', 'Not available for this place', '+14167921784', '+14169663888', '+14169772828', '+14165464557', '+14169271231', '+14166251899', '+16473418686', '+16473525466', '+14165992855', '+14163488828', '+14164084999', '+14165199995', '+16477484488', '+14168400501', '+14169299964', '+16473477713', '+14168668200', '+14169959639', '+18447678368', '+14169258454', '+14167928628', '+16473522207', '+14165042334', '+16473463030', '+14165464536', '+16473523627', '+14165513366', '+16474471707', '+14168408930', '+14163646183', '+14165042188', '+16473462172', '+14165911245', '+14165045709', '+14166033337', '+14162059227', '+14165939747', '+16479698881', '+14169025632', '+14165956405', '+14169227423', '+16473497767', '+16475021291', '+14163489200', '+14165334101', '+14165332822', '+14165343447', '+14165363132', '+14165882699', '+16473429229', '+14165343100', '+14166450285', '+14165317755', '+14165511550', '+14165347867', '+16473458838', '+14165339619', '+14165358424', '+14165168688', '+14168504579', '+14165302738', '+14166450117', '+14165342942', '+16473481133', '+14166032515', '+14169640606', '+14169015859', '+14165351888', '+14165322518', '+14167388313', '+14165364564', '+14165315833', '+14165886006', '+14165341107', '+16473418882', '+14165350613', '+14165320419', '+16473487467', '+14165162549', '+14165517647', '+16477487839', '+14169726859', '+14165338841', '+16473481686', '+14165347441', '+14165463495', '+14167033433', '+14167928890', '+14169221703', '+16473507687', '+14166037817', 'Not available for this place', '+14165511322', '+14169671111', '+14168416673', '+14165342856', '+16473306611', '+16473525520', '+14169646006', 'Not available for this place', '+14167363636', '+14165339722', '+16474279307', '+14168619872', '+16473514612', '+16473506999', '+14169477000', '+14163699048', '+14167031560', '+14163667800', '+14168627575', '+16472602070', '+14168600086', '+14163670303', '+14168679499', '+14168686668', '+14168649761', '+14163667827', '+14165049998', '+14162145888', '+16473413642', '+14169610601', '+14165042253', '+14169000949', '+16473441562', '+14163634247', '+14163664567', '+14163627373', '+14165949675', '+14168402759', '+14168647373', '+14168627676', '+14163648368', '+16473523300', '+14162031635', '+14168630000', '+14168668282', '+14163681300', '+14168621999', '+14163637100', '+14168502726', '+16473440088', '+16478961774', '+14165041311', '+14163670685', '+14169479500', '+14163678325', '+14163648305', '+14163660303', '+14163646572', '+14163040550', '+14163632020', '+14163686955', '+16479309517', '+14163690330', '+14164152260', '+16473488811', '+14163643764', '+14168501738', '+14167927725', '+14163630202', '+14163688048', '+14166019444', '+14163664841', '+14163689988', '+16477482582', '+16473512378', '+14163623444', '+14169411474', '+14163664040', '+14163645811', '+14168634125', '+14169951530', '+14163634663', '+14168699191', '+16473473309', '+14169550887', '+14168609000', '+14168157562', '+14162149918', '+14168689595', '+14168400268', '+14163689030', '+14169133361', '+14166996100', '+14166919009', '+14166861998', '+14164058189', '+14166909985', '+14166865688', '+14166967392', '+14166905516', '+14165194534', '+14166993874', '+14166901984', '+14166987705', '+14166912788', '+14166918784', '+14166868541', '+14166982120', '+14166905959', '+14166994444', '+14166902813', '+14166943056', '+14165517727', '+16473516112', '+14166949696', '+14166988131', '+14166908880', '+14166935775', '+14166919200', '+16477482232', '+14166906906', '+14166901782', '+14166938724', '+16473502261', '+16473506500', '+14166902420', '+14166998272', '+16477486288', '+14166980555', '+14166940443', '+14166993340', '+14166867153', '+14164661234', '+14166980700', '+16473523818', '+16473493016', '+14166909900', '+16473482009', '+14169139977', '+14166918080', '+14164693065', '+16473438484', '+14166994000', '+16473475047', '+16477489233', '+14166862391', '+16474646541', '+14166981698', '+16477487977', '+14166995699', '+14166939337', '+14166985567', '+14163101010', '+16473440090', '+14166989885', '+16478279070', '+14166062268', '+14166983354', '+14166983456', '+14166903867', '+14166900707', '+16473413276', '+14168495064', '+14168941956', '+16473529300', '+16473524555', '+14166945000', '+14164662422', '+14166986036', '+14166949339', '+14166985548', '+14164695225', '+14164666555', '+14164622703', '+14164668800', '+14168491233', '+14164061301', '+14164695797', '+14164062525', '+16473455626', '+16473471168', '+14164652006', '+14167780111', '+14164629666', '+14164630114', '+14164658085', '+14168557331', '+14164658448', '+14167924157', '+16474354779', '+14164618424', '+14169011177', '+16473401738', '+14164613111', '+14164635663', '+14164058080', '+14166867066', '+14167787366', '+14164615663', '+16473414070', '+14164693010', '+14164639292', '+14164694444', '+14164699696', '+14164612988', '+14164650955', '+14164064511', '+14169019233', '+14167784440', '+14164639777', '+14167921590', '+16473521463', '+14164061815', '+16473515535', '+14164668934', '+14169166432', '+14164615848', '+14164631818', '+16473506263', '+14167926210', '+14164694466', 'Not available for this place', '+14169167895', '+14164666241', '+14167780303', '+14164615030', '+14164635302', '+14167784343', '+14168551460', '+14164663185', '+14164650836', '+16473478640', '+14164619788', '+14167275411', '+14162004606', '+14164620828', '+16473452762', '+14164694323', '+14166911284', '+14167789785', '+14164619111', '+16473401218', '+16473488424', '+16473522206', 'Not available for this place', '+16477487740', '+16473472677', '+14162202915', '+16473527781', '+14164669261', 'Not available for this place', '+14164660400', '+14167785150', '+14164632838', '+14164612571', '+14164633086', '+14164662000', '+14167781929', '+14164695183', '+14164668158', '+16477057880', '+14164650969', '+14164654356', '+14167780500', '+16473522799', '+14164634418', '+14164663388', '+14164699595', '+14164064688', '+14167928088', '+14164692270', '+14164633333', '+14164665273', '+14164635144', '+16473477867', '+14169164388', '+14164662931', '+14169018663', '+14164632655', '+14164698422', '+16473505087', '+14164637843', '+14167787896', '+14167787004', '+14164060288', '+14165462148', '+14164619577', '+14164667771', '+14167784444', '+14164619238', '+16473517433', '+14164652125', '+14167786654', '+14164634927', '+14167925252', '+14164618294', '+14164610136', '+14167927788', '+14168554240', '+14164662129', '+14164669933', '+14164652253', '+14164629830', '+14164692124', '+14164654441', '+14167598484', '+14165533833', '+14164622735', '+14164062500', '+14164615546', '+14169011991', '+14164658175', '+14164613073', '+14164632667', '+14164699565', '+14164618500', '+14164653364', '+14163638580', '+14164663403', '+16473478720', '+14164616968', '+14164666500', '+14164620693', '+14165192633', '+14164633968', '+14164058100', '+14164666295', '+18775994438', '+14169151515', '+14165192798', '+14164058877', '+14164063121', '+14164613020', '+14164637792', '+14164254664', '+16473467771', '+14164221870', '+14164058074', '+14164692513', '+14164220617', '+14164060880', '+14166982168', '+14164662345', '+14166995865', '+14164660648', '+16473483028', '+14164631794', '+14166938424', '+16473518696', '+14166945811', '+14166980283', '+14164294665', '+14166902278', '+14164665713', '+14166450486', '+14169160901', '+14164611198', '+14166942323', '+14164661965', '+14164632655', '+14164257717', '+16477481376', '+14166668875', '+14164060534', '+16473447466', '+14166907406', '+14168373254', '+14166901308', '+14164666435', '+16474495999', '+16473488622', '+14166998812', '+16477481235', '+14164252895', '+14164654224', '+16479721401', '+14169013001', '+14166989166', '+14166987716', '+16473501917', '+14164216635', '+14166918828', '+14164657542', '+14166919364', '+14166948720', '+14164219990', '+14166932222', '+16477069865', '+16473458382', '+14165517560', '+14164665130', '+16473524888', 'Not available for this place', '+14164615551', '+14165518070', '+14166932057', '+16473451504', '+14166939018', '+16473477616', '+14164221870', '+14166867191', '+14166991248', '+16473447278', '+16477485088', '+14164390000', '+14166910469', '+14164233603', '+14164691524', '+14162410241', '+14164690782', '+14169671111', '+14164882031', '+14164833747', '+14164871974', '+14164890630', '+14164844646', '+14164832590', '+14164806234', '+14164866644', '+14163226767', '+14164851244', '+14164817111', '+16473523624', '+14164818181', '+14163225678', '+16473480337', '+14163226184', '+14169328891', '+14165994442', '+14165516800', '+14164885774', '+14163226860', '+14164877070', '+14163228861', '+14163225463', '+14164883242', '+14164862222', '+14164853447', '+14164894163', '+16477486300', '+14163223267', '+14165440777', '+14169250016', '+14164855552', '+14163226648', '+14163223563', '+14164401986', '+14164833888', '+14164838432', '+14163227111', '+14165194545', '+14164892233', '+14164816865', '+14164800202', '+16473460125', '+16477487101', '+14169322811', '+16473436744', '+14164869006', '+14164867469', '+14164819111', '+14165984003', '+14164830697', '+16473510130', '+14165515527', '+14169320290', '+14164878660', '+14164856464', '+14164800200', '+14169328349', '+16477483633', '+14164821616', '+16473525288', '+14169877288', '+14164893500', '+14164892153', '+14164877673', '+16473487661', '+14164800303', '+14164810008', '+19056445051', '+14164882110', '+14168492214', '+14164849080', '+14165450000', '+14164819397', '+16473527825', '+14164852290', '+16473514130', '+14163220609', '+14164813555', '+14169013211', '+14167671315', '+14167632253', '+14167660993', '+14166048822', '+14165515199', '+16477487666', '+14167679222', '+14167699898', '+14167699336', '+14167611811', '+14167698866', '+16473454466', '+14167677246', '+14166288337', '+14166042321', '+14167670608', '+14165368494', '+14167636164', '+14167671077', '+14167663293', '+14167678882', '+14167662252', '+16477486153', '+14167677200', '+14167665383', '+16473471977', '+14167699991', '+14167869771', '+16478495204', '+14168046066', '+14167629949', '+16473453466', '+14167623036', '+16477489292', '+14165360458', '+14167633200', '+14167924542', '+16478641654', '+14167697827', '+14167676409', '+14167631572', '+14162418187', '+14167678910', '+14169671111', '+14169671111', '+14167679661', '+14166044055', '+16479328311', '+14167668899', '+14169671111', '+14167631818', '+14167620505', '+14167611026', '+16473442935', '+14167697788', '+14167675212', '+14167363636', '+14167624441', '+14167622348', '+14167619402', '+16477660349', '+14167678830', '+16473527767', '+14167634191', '+14167609691', '+16474303909', '+16473433600', '+14167695460', '+14169162368', '+14166049465', '+14167622103', '+14167673131', '+16473503564', '+14167608208', '+14169017468', '+16474786388', '+16473502975', '+14169075787', '+14167695736', '+14162522166', '+14162333046', '+14165462093', '+14162552808', '+14162513337', '+14166401015', '+14162322320', '+14162555588', '+14165038288', '+14162557746', '+14166747500', '+16477482350', '+14162369588', '+14162557455', '+14162511144', '+16473484525', '+14162520202', '+14162316688', '+14165971999', '+14168627175', '+14162070596', '+14162512699', '+14162341148', '+14168487424', '+14162313800', '+14166747777', '+16473505140', '+14162521566', '+14162590440', '+14168503721', '+14162590050', '+14162556553', '+16473488654', '+14162017392', '+14162486163', '+14168490344', '+16473484848', '+14165191355', '+14162591846', '+14162555081', '+14166226677', '+14166220222', '+14168505935', '+14162539959', '+14162392222', '+14162311367', '+14162395000', '+14162556464', '+14162525000', '+14162079940', '+14162335004', '+14162499666', '+14162550464', '+14165030850', '+14162392824', '+14167459430', '+14167454189', '+14162510101', '+14165353337', '+14162379414', '+14162360081', '+14166216255', '+14165217444', '+14162396244', '+14167626292', '+14167986788', '+14162337406', '+14162362701', '+14162527700', '+14162365959', '+14163542699', '+16473528448', '+14162391286', '+14166209229', '+14166752311', '+14167920054', '+14162517177', '+14166262700', '+14162342233', '+14162554224', '+14163210250', '+14164909688', '+14164399234', '+14164313565', '+14162872020', '+14162994141', '+14162976100', '+14164978899', '+14162932444', '+16477641188', '+14162881588', '+14162968803', '+14164396804', '+14164918484', '+14162937755', '+14162982998', '+14167573945', '+14162988081', '+14162971438', '+14162936696', '+14162989978', '+14162832112', '+14167562788', '+14164988848', '+14167513100', '+14162652695', '+14162695757', '+16473407099', '+14167010003', '+14167508898', '+14164381452', '+14162664565', '+14162858191', '+16473400109', '+14162983828', '+14163218288', '+14164912507', '+14162961400', '+14167240970', '+14162916340', '+14167555757', '+14169168101', '+16477489229', '+14162910123', '+14164456721', '+14162984153', '+14162820121', '+14167525685', '+14162975375', '+14162851337', '+14163328807', '+14163351177', '+14163210888', '+14167548141', '+14163350336', '+14162960965', '+14169011133',

In [29]:
zomato_df['phone'] = phones_new
zomato_df.head(25)

,name,id,phone,reservations,price_range,review,rating
0,Trattoria Nervosa,8908253,+14169614642,0,3,282,4.3
1,Sabai Sabai,8904233,+16477484225,0,2,250,4.6
2,Café Boulud,8910669,+14169636000,0,4,162,4.6
3,La Société,8906782,+14165519929,0,3,177,4.0
4,Buca Osteria & Bar,8911003,+14169622822,0,3,83,4.6
5,Hemingway Bar & Restaurant,8908161,+14169682828,0,3,174,3.9
6,Yamato,8907980,+14169270077,0,4,184,4.2
7,Sushi Inn,8908568,+14169239992,0,2,171,4.0
8,Dimmi,8908011,+14169751100,0,3,126,4.2
9,Courtyard Cafe - Windsor Arms,8909734,+14169719666,0,4,83,4.2
10,Kothur Indian Cuisine,8909058,+14169260953,0,2,117,4.0
11,Blu Ristorante,8908626,+14169211471,0,3,82,4.1
12,Museum Tavern,8907586,+14169260110,0,3,86,4.0
13,Lee Chen,8908607,+14169018869,0,2,85,4.0
14,Joso's,8910877,+14169251903,0,4,109,4.2
15,Kasa Moto,16547632,+16473487000,0,4,34,3.9
16,Over Easy,8906876,+14169222345,0,2,96,3.7
17,Utsav,8907503,+14169618349,0,2,86,4.1
18,Paramount Fine Foods,17758625,+14169603434,0,2,38,3.8
19,The Bagel Stop,8907359,+14169753948,0,1,97,3.4
20,Dynasty Chinese,8911904,+14169233323,0,3,77,3.7
21,Summer's,8908080,+14169442637,0,1,83,4.3
22,Carole's Cheesecake Cafe,8908193,+14168491499,0,1,67,3.9
23,The Pilot,8908179,+14169235716,0,3,75,3.8
24,Aji Sai,8908864,+14169691221,0,3,77,4.0

In [30]:
#Save to a CSV all data retrieved
zomato_df.to_csv("Toronto_zomato.csv", sep=',',index=False)

In [31]:
import pymysql
pymysql.install_as_MySQLdb()

from sqlalchemy import create_engine
engine = create_engine("mysql://root:367Tanner#@localhost/restaurant_review")

In [32]:
toronto_df = zomato_df
toronto_df.dtypes

name            object
id              object
phone           object
reservations    object
price_range      int64
review          object
rating          object
dtype: object

In [33]:
toronto_df.to_sql(
                name='zomato',
                con=engine, 
                if_exists="append"
                 )

InternalError: (pymysql.err.InternalError) (1366, "Incorrect string value: '\\xC5\\x8D' for column 'name' at row 104")
[SQL: INSERT INTO zomato (`index`, name, id, phone, reservations, price_range, review, rating) VALUES (%(index)s, %(name)s, %(id)s, %(phone)s, %(reservations)s, %(price_range)s, %(review)s, %(rating)s)]
[parameters: ({'index': 0, 'name': 'Trattoria Nervosa', 'id': '8908253', 'phone': '+14169614642', 'reservations': '0', 'price_range': 3, 'review': '282', 'rating': '4.3'}, {'index': 1, 'name': 'Sabai Sabai', 'id': '8904233', 'phone': '+16477484225', 'reservations': '0', 'price_range': 2, 'review': '250', 'rating': '4.6'}, {'index': 2, 'name': 'Café Boulud', 'id': '8910669', 'phone': '+14169636000', 'reservations': '0', 'price_range': 4, 'review': '162', 'rating': '4.6'}, {'index': 3, 'name': 'La Société', 'id': '8906782', 'phone': '+14165519929', 'reservations': '0', 'price_range': 3, 'review': '177', 'rating': '4.0'}, {'index': 4, 'name': 'Buca Osteria & Bar', 'id': '8911003', 'phone': '+14169622822', 'reservations': '0', 'price_range': 3, 'review': '83', 'rating': '4.6'}, {'index': 5, 'name': 'Hemingway Bar & Restaurant', 'id': '8908161', 'phone': '+14169682828', 'reservations': '0', 'price_range': 3, 'review': '174', 'rating': '3.9'}, {'index': 6, 'name': 'Yamato', 'id': '8907980', 'phone': '+14169270077', 'reservations': '0', 'price_range': 4, 'review': '184', 'rating': '4.2'}, {'index': 7, 'name': 'Sushi Inn', 'id': '8908568', 'phone': '+14169239992', 'reservations': '0', 'price_range': 2, 'review': '171', 'rating': '4.0'}  ... displaying 10 of 1500 total bound parameter sets ...  {'index': 1498, 'name': "Anna's Bakery & Pastry", 'id': '8909613', 'phone': '+14167698065', 'reservations': '0', 'price_range': 1, 'review': 2, 'rating': 0}, {'index': 1499, 'name': 'Indian Sweets & Samosa', 'id': '17873524', 'phone': '+14162497777', 'reservations': '0', 'price_range': 1, 'review': 2, 'rating': 0})]
(Background on this error at: http://sqlalche.me/e/2j85)